FROM --platform=$BUILDPLATFORM php:8.0-apache AS build
# Copy application source
COPY ./php/src /var/www/html/

ARG TARGETPLATFORM
RUN build --target=$TARGETPLATFORM /php/src

RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

FROM php:8.0-apache
COPY --from=build /php/src /php/src

EXPOSE  80